### ISSUE TITLE
Write something in BEGINNER/s2-functions-loops/loops.py

### ISSUE THREAD

**Issue by stvnliu** [stvnliu/byron-college-coding-club#4]
```
# TODO
```

https://github.com/zhongheng-liu/alan-turing-coding-club/blob/c6e881c2fe6fdf56ba96fa3b88f8242e31b22096/BEGINNER/s2-functions-loops/loops.py#L1

**Comment by Ate329** [comment]
okok

**Comment by Ateee329** [comment]
done

**Comment by Ate329** [comment]
done
