### ISSUE TITLE
I'm not sure whether slicing strings and string methods should be in s1 intro basics

### ISSUE THREAD

**Issue by Ate329** [stvnliu/byron-college-coding-club#5]
it might be too much for them for basics idk, we can move it to s3 and expand more about string methods

**Comment by stvnliu** [comment]
s3 is too much. recommend move to s2

**Comment by Ate329** [comment]
what r u planning to put in s3. I'm thinking of put strings as an individual session cuz there are a lot to talk about

**Comment by stvnliu** [comment]
I think s3 will be about loops and arrays. s4 will be about building a GUI library

**Comment by Ate329** [comment]
ok gud
